routes/web.php
<?php

use App\Http\Controllers\AnswersController;
use App\Http\Controllers\Frontend\FrontendAnswersController;
use App\Http\Controllers\Frontend\FrontendQuestionsController;
use App\Http\Controllers\Frontend\FrontendTagsController;
use App\Http\Controllers\Frontend\FrontendUsersController;
use App\Http\Controllers\QuestionsController;
use App\Http\Controllers\TagsController;
use App\Http\Controllers\UsersController;
use App\Http\Controllers\VotesController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();
/* AUTH ROUTES */
Route::middleware(['auth'])->group(function() {

    /* QUESTION */
    Route::resource('questions', QuestionsController::class)->except('show', 'create', 'edit');

    /* TAGS */
    Route::resource('tags', TagsController::class)->except('show', 'create', 'edit');

    /* ANSWER */
    Route::resource('questions.answers', AnswersController::class)->except('show', 'create', 'edit');
    Route::put('questions/{question}/answers/{answer}/mark-as-best', [QuestionsController::class, 'markAsBest'])->name('questions.answers.markAsBest');

    /* USER */
    Route::resource('users', UsersController::class)->except('show', 'create', 'edit');
});

/* FRONTEND ROUTES */

/* Question */
Route::get('/', [FrontendQuestionsController::class, 'index'])->name('frontend.questions.index');
Route::get('/questions/create', [FrontendQuestionsController::class, 'create'])->name('frontend.questions.create');
Route::get('/questions/{question}', [FrontendQuestionsController::class, 'show'])->name('frontend.questions.show');
Route::get('/questions/{question}/edit', [FrontendQuestionsController::class, 'edit'])->name('frontend.questions.edit');
Route::post('/questions/{question}/votes/{vote}', [VotesController::class, 'voteQuestion'])->name('questions.vote');

/* Tag */
Route::get('/tags', [FrontendTagsController::class, 'index'])->name('frontend.tags.index');
Route::get('/tags/create', [FrontendTagsController::class, 'create'])->name('frontend.tags.create');
Route::get('/tags/{tag}', [FrontendTagsController::class, 'show'])->name('frontend.tags.show');
Route::get('/tags/{tag}/edit', [FrontendTagsController::class, 'edit'])->name('frontend.tags.edit');

/* User */
Route::get('/users', [FrontendUsersController::class, 'index'])->name('frontend.users.index');
Route::get('/users/notifications', [FrontendUsersController::class, 'notifications'])->name('frontend.users.notifications'); // internally the auth()->id() will be taken by me
Route::get('/users/{user}', [FrontendUsersController::class, 'show'])->name('frontend.users.show');
Route::get('/users/{user}/edit', [FrontendUsersController::class, 'edit'])->name('frontend.users.edit');

/* Answer */
Route::get('/questions/{question}/answers/{answer}', [FrontendAnswersController::class, 'edit'])->name('frontend.questions.answers.edit');
Route::post('/questions/{question}/answers/{answer}/votes/{vote}', [VotesController::class, 'voteAnswer'])->name('questions.answers.vote');

app/Models/Tag.php
<?php

namespace App\Models;

use App\DTO\Tags\TagDTO;
use Carbon\Carbon;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Tag extends Model
{
    use HasFactory;

    protected $guarded = ['id'];
    /**
     * RELATIONSHIP METHODS
     */
    public function creator()
    {
        return $this->belongsTo(User::class, 'user_id');
    }
    public function questions()
    {
        return $this->belongsToMany(Question::class)->withTimestamps();
    }

    /**
     * HELPER METHODS
     */
    public function toDTO(): TagDTO
    {
        return new TagDTO(
            id: $this->id,
            name: $this->name,
            desc: $this->desc,
            creator: $this->creator->toDTO(),
            questions: gettype($this->questions) == 'array' ? $this->questions : null,
            created_at: $this->created_at,
            updated_at: $this->updated_at,
            created_date: (new Carbon($this->created_at))->diffForHumans(),
            updated_date: (new Carbon($this->updated_at))->diffForHumans(),
        );
    }
}

app/Http/Controllers/Frontend/FrontendAnswersController.php
<?php

namespace App\Http\Controllers\Frontend;

use App\DTO\Answers\AnswerDTO;
use App\DTO\Questions\QuestionDTO;
use App\Http\Controllers\Controller;
use App\Models\Answer;
use App\Models\Question;

class FrontendAnswersController extends Controller
{
    public function edit(Question $question, Answer $answer)
    {
        $questionDTO = new QuestionDTO(...$question->toArray());
        $question = $questionDTO;
        $answerDTO = new AnswerDTO(...$answer->toArray());
        $answer = $answerDTO;
        return view('frontend.answers.edit', compact(['question','answer']));
    }
}

app/Http/Controllers/Frontend/FrontendQuestionsController.php
<?php

namespace App\Http\Controllers\Frontend;

use App\Http\Controllers\Controller;
use App\Models\Question;
use App\Models\Tag;
use App\Services\QuestionService;

class FrontendQuestionsController extends Controller
{
    private $questionService;
    public function __construct()
    {
        $this->middleware('can:performAuthorActions,question')->only('edit');
        $this->questionService = new QuestionService();
    }
    public function index()
    {
        $questions = $this->questionService->index();
        return view('frontend.questions.index', compact(['questions']));
    }

    public function show(int $id)
    {
        $question = $this->questionService->show($id);
        return view('frontend.questions.show', compact(['question']));
    }

    public function create()
    {
        $tags = Tag::all();
        return view('frontend.questions.create', compact(['tags']));
    }

    public function edit(Question $question)
    {
        $tags = Tag::all();
        return view('frontend.questions.edit', compact(['question', 'tags']));
    }

}

app/Http/Controllers/Frontend/FrontendTagsController.php
<?php

namespace App\Http\Controllers\Frontend;

use App\Http\Controllers\Controller;
use App\Models\Tag;
use Illuminate\Http\Request;

class FrontendTagsController extends Controller
{
    public function __construct()
    {
        $this->middleware('can:update,tag')->only('edit');
    }

    public function index()
    {
        $tags = Tag::with('creator')->latest()->paginate(15);
        return view('frontend.tags.index', compact(['tags']));
    }

    public function show(int $id)
    {
        $tag = Tag::with('creator')->findOrFail($id);
        $questions = $tag->questions()->latest()->paginate(3);
        return view('frontend.tags.show', compact(['tag', 'questions']));
    }

    public function create()
    {
        return view('frontend.tags.create');
    }

    public function edit(Tag $tag)
    {
        return view('frontend.tags.edit', compact(['tag']));
    }

}

app/Http/Controllers/Frontend/FrontendUsersController.php
<?php

namespace App\Http\Controllers\Frontend;

use App\Http\Controllers\Controller;
use App\Models\User;
use Illuminate\Http\Request;

class FrontendUsersController extends Controller
{
    public function __construct()
    {
        $this->middleware('can:update,user')->only('edit');
    }
    public function index()
    {
        $users = User::latest()->paginate(10);
        return view('frontend.users.index', compact(['users']));
    }
    public function show(User $user)
    {
        $questions = $user->questions()->latest()->paginate(3);
        return view('frontend.users.show', compact(['user', 'questions']));
    }
    public function edit(User $user)
    {
        return view('frontend.users.edit', compact(['user']));
    }
    public function notifications()
    {
        $notifications = auth()->user()->notifications()->latest()->simplePaginate(10);
        return view('frontend.users.notifications', compact(['notifications']));
    }
}

app/Http/Controllers/TagsController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\Tags\CreateTagRequest;
use App\Http\Requests\Tags\UpdateTagRequest;
use App\Models\Tag;
use Illuminate\Http\Request;

class TagsController extends Controller
{
    public function __construct()
    {
        $this->middleware('can:update,tag')->only('update');
        $this->middleware('can:delete,tag')->only('delete');
    }

    public function store(CreateTagRequest $request)
    {
        auth()->user()->tags()->create([
            'name' => $request->name,
            'desc' => $request->desc
        ]);
        return redirect(route('frontend.tags.index'));
    }

    public function update(UpdateTagRequest $request, Tag $tag)
    {
        $tag->update([
            'name' => $request->name,
            'desc' => $request->desc
        ]);
        return redirect(route('frontend.tags.show', $tag->id));
    }

    public function destroy(Tag $tag)
    {
        $tag->delete();
        return redirect(route('frontend.tags.index'));
    }
}

resources/views/frontend/tags/create.blade.php
@extends('layouts.frontend.layout')

@section('title', 'Create a Tag')

@section('hero-header-left')
    <h2 class="hero-title m-0">Create a Tag</h2>
@endsection

@section('hero-body')
    <div class="bg-white p16 br-10">
        <form action="{{route('tags.store')}}" class="m-0" method="POST" enctype="multipart/form-data">
            @csrf
            <div class="form-group">
                <label class="mb4">Name</label>
                <input type="text"
                       name="name"
                       value="{{old('name')}}"
                       class="form-control br-10 p12"
                       placeholder="eg: programming">
                @error('name')
                    <small id="errorHelp" class="form-text text-danger">{{ $message }}</small>
                @enderror
            </div>
            <div class="form-group">
                <label class="mb4">Description</label>
                <textarea type="text"
                       name="desc"
                       value="{{old('desc')}}"
                       class="form-control br-10 p12"
                       placeholder="Give some brief information about the tag"></textarea>
                @error('desc')
                    <small id="errorHelp" class="form-text text-danger">{{ $message }}</small>
                @enderror
            </div>

            <div class="form-group text-right">
                <button type="submit" class="btn btn-success py8">Submit</button>
            </div>
        </form>
    </div>
@endsection

resources/views/frontend/tags/edit.blade.php
@extends('layouts.frontend.layout')

@section('title', 'Edit a Tag')

@section('hero-header-left')
    <h2 class="hero-title m-0">Edit a Tag</h2>
@endsection

@section('hero-body')
    <div class="bg-white p16 br-10">
        <form action="{{route('tags.update', $tag->id)}}" class="m-0" method="POST" enctype="multipart/form-data">
            @csrf
            @method('PUT')
            <div class="form-group">
                <label class="mb4">Name</label>
                <input type="text"
                       name="name"
                       value="{{old('name', $tag->name)}}"
                       class="form-control br-10 p12"
                       placeholder="eg: programming">
                @error('name')
                    <small id="errorHelp" class="form-text text-danger">{{ $message }}</small>
                @enderror
            </div>
            <div class="form-group">
                <label class="mb4">Description</label>
                <textarea type="text"
                       name="desc"
                       class="form-control br-10 p12"
                       placeholder="Give some brief information about the tag">{{old('desc', $tag->desc)}} </textarea>
                @error('desc')
                    <small id="errorHelp" class="form-text text-danger">{{ $message }}</small>
                @enderror
            </div>

            <div class="form-group text-right">
                <button type="submit" class="btn btn-success py8">Submit</button>
            </div>
        </form>
    </div>
@endsection

resources/views/frontend/tags/index.blade.php
@extends('layouts.frontend.layout')

@section('title', 'Tags')

@section('hero-header-left')
    <h2 class="hero-title m-0">Tags</h2>
    <div class="d-flex align-items-center my8 w100">
        <p class="count m-0">{{$tags->count()}} users</p>
        <ul class="fast-filters list-group list-group-horizontal align-items-center">
            <li class="list-group-item list-group-item-action p-0">
                <a href="" class="fast-filter">Newest</a>
            </li>
            <li class="list-group-item list-group-item-action p-0">
                <a href="" class="fast-filter">Popular</a>
            </li>
        </ul>
        <form action="" class="input-group d-flex search-field w25">
            <input type="text"
                    name="tag-search"
                    value="{{ request('search')}}"
                    class="form-control"
                    placeholder="Search a tag...">
            <div class="input-group-append">
                <button type="submit" name="submit" class="btn btn-sm bg-white">
                    <i class="bi bi-search"></i>
                </button>
            </div>
        </form>
    </div>
@endsection

@section('hero-header-right')
    <a href="{{route('frontend.tags.create')}}" class="btn btn-primary py12 px20">Create a Tag</a>
@endsection

@section('hero-body')
    @foreach ($tags as $tag)
        <div class="section-card d-inline-block tag-card mb12 mr20 p16">
            <a href="{{route('frontend.tags.show', $tag->id)}}" class="m-0 tag badge badge-pill bg-outline-info">{{$tag->name}}</a>
            <div class="tag-desc my12">
                {!! \Illuminate\Support\Str::limit($tag->desc, 30)!!}
            </div>
            <div class="questions-count">
                <i class="bi bi-question-circle mr8"></i>
                <span>{{$tag->questions->count()}} questions</span>
            </div>
        </div>
    @endforeach
@endsection
@section('hero-footer')
    {{ $tags->links() }}
@endsection

resources/views/frontend/tags/show.blade.php
@extends('layouts.frontend.layout')

@section('title', 'Questions')

@section('hero-header-left')
    <h2 class="hero-title m-0">Questions tagged in [{{$tag->name}}]</h2>
    <p class="mt12">{!!$tag->desc!!}</p>
    <p class="count mt8">{{$questions->count()}} questions</p>
@endsection

@section('hero-header-right')
    <a href="{{route('frontend.questions.create')}}" class="btn btn-primary py12 px20">Ask a question</a>
    @can('update', auth()->user())
        <a href="{{route('frontend.tags.edit', $tag->id)}}" class="btn btn-sm btn-outline-info py12 px20">
            <i class="bi bi-pencil-square mr4"></i>Edit
        </a>
    @endcan
    @can('delete', auth()->user())
        <button
            type="button"
            onclick="displayDeleteTagModal({{$tag->id}})"
            class="btn btn-sm btn-outline-danger py12 px20" data-toggle="modal"
            data-target="#deleteTagModal">
            <i class="bi-x-square mr4"></i> Delete
        </button>
    @endcan
@endsection

@section('hero-body')
    @foreach ($questions as $question)
        <div class="section-card mb12 p16">
            <div class="author-image mr12">
                <img src="{{$question->author->avatar}}" alt="User image">
            </div>
            <div class="section-details">
                <div class="section-header">
                    <span class="user-info">Asked by: <a href="" class="author-name">{{$question->author->name}}</a> {{$question->created_date}}</span>
                    <div class="tags-container">
                        <span class="ml12">Tags:</span>
                        <div class="tags">
                            @foreach ($question->tags as $tag)
                                <a href="{{route('frontend.tags.show', $tag->id)}}" class="tag badge badge-pill bg-outline-info">{{$tag->name}}</a>
                            @endforeach
                        </div>
                    </div>
                </div>
                <div class="section-body">
                    <a href="{{route('frontend.questions.show', $question->id)}}"  class="section-title">{{$question->title}}</a>
                    <p class="section-content">{!! \Illuminate\Support\Str::limit($question->body, 200) !!}</p>
                </div>
                <div class="section-footer d-flex mt8">
                    <div class="section-stats">
                        <div class="stat answers-count">
                            <i class="bi bi-chat-right mr8"></i>{{$question->answers_count}} answers
                        </div>
                        <div class="stat upvotes-count">
                            <i class="bi bi-caret-up-fill mr8"></i>{{$question->upvotes_count}} upvotes
                        </div>
                        <div class="stat views-count">
                            <i class="bi bi-eye-fill mr8"></i>{{$question->views_count}} views
                        </div>
                        <span class="stat best-answer-badge">
                            <i class="bi bi-check-circle mr8"></i>Best answer given by Jane Doe
                        </span>
                    </div>
                    <div class="view-question-btn-container">
                        <a href="{{route('frontend.questions.show', $question->id)}}"  class="view-question-btn br-10 btn btn-sm btn-outline-primary no-border">View this question</a>
                    </div>

                </div>
            </div>
        </div>
    @endforeach
        @include('frontend.tags.partials._modals')
@endsection
@section('hero-footer')
    {{-- {{ $questions->links() }} --}}
@endsection

@section('page-level-scripts')
    <script>
        function displayDeleteTagModal($tagId) {
            var url = '/tags/' + $tagId;
            $('#deleteTagForm').attr('action', url);
        }
    </script>
@endsection