routes/web.php
<?php

use App\Http\Controllers\AnswersController;
use App\Http\Controllers\Frontend\FrontendAnswersController;
use App\Http\Controllers\Frontend\FrontendQuestionsController;
use App\Http\Controllers\Frontend\FrontendTagsController;
use App\Http\Controllers\Frontend\FrontendUsersController;
use App\Http\Controllers\QuestionsController;
use App\Http\Controllers\TagsController;
use App\Http\Controllers\UsersController;
use App\Http\Controllers\VotesController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();
/* AUTH ROUTES */
Route::middleware(['auth'])->group(function() {

    /* QUESTION */
    Route::resource('questions', QuestionsController::class)->except('show', 'create', 'edit');

    /* TAGS */
    Route::resource('tags', TagsController::class)->except('show', 'create', 'edit');

    /* ANSWER */
    Route::resource('questions.answers', AnswersController::class)->except('show', 'create', 'edit');
    Route::put('questions/{question}/answers/{answer}/mark-as-best', [QuestionsController::class, 'markAsBest'])->name('questions.answers.markAsBest');

    /* USER */
    Route::resource('users', UsersController::class)->except('show', 'create', 'edit');
});

/* FRONTEND ROUTES */

/* Question */
Route::get('/', [FrontendQuestionsController::class, 'index'])->name('frontend.questions.index');
Route::get('/questions/create', [FrontendQuestionsController::class, 'create'])->name('frontend.questions.create');
Route::get('/questions/{question}', [FrontendQuestionsController::class, 'show'])->name('frontend.questions.show');
Route::get('/questions/{question}/edit', [FrontendQuestionsController::class, 'edit'])->name('frontend.questions.edit');
Route::post('/questions/{question}/votes/{vote}', [VotesController::class, 'voteQuestion'])->name('questions.vote');

/* Tag */
Route::get('/tags', [FrontendTagsController::class, 'index'])->name('frontend.tags.index');
Route::get('/tags/create', [FrontendTagsController::class, 'create'])->name('frontend.tags.create');
Route::get('/tags/{tag}', [FrontendTagsController::class, 'show'])->name('frontend.tags.show');
Route::get('/tags/{tag}/edit', [FrontendTagsController::class, 'edit'])->name('frontend.tags.edit');

/* User */
Route::get('/users', [FrontendUsersController::class, 'index'])->name('frontend.users.index');
Route::get('/users/notifications', [FrontendUsersController::class, 'notifications'])->name('frontend.users.notifications'); // internally the auth()->id() will be taken by me
Route::get('/users/{user}', [FrontendUsersController::class, 'show'])->name('frontend.users.show');
Route::get('/users/{user}/edit', [FrontendUsersController::class, 'edit'])->name('frontend.users.edit');

/* Answer */
Route::get('/questions/{question}/answers/{answer}', [FrontendAnswersController::class, 'edit'])->name('frontend.questions.answers.edit');
Route::post('/questions/{question}/answers/{answer}/votes/{vote}', [VotesController::class, 'voteAnswer'])->name('questions.answers.vote');

app/Models/Question.php
<?php

namespace App\Models;

use App\Constants\QuestionConstants;
use App\DTO\Questions\QuestionDTO;
use App\Helpers\Utils;
use App\Helpers\Votable;
use Carbon\Carbon;
use Exception;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class Question extends Model implements QuestionConstants
{
    use HasFactory, Votable;

    protected $guarded = ['id'];

    /**
     * HELPER METHODS
     */
    public function hasTag(int $tag_id):bool
    {
        return in_array($tag_id, $this->tags->pluck('id')->toArray());
    }

    public function toDTO(): QuestionDTO
    {
        $authUser = auth()->user();
        return new QuestionDTO(
            id: $this->id,
            title: $this->title,
            slug: $this->slug,
            body: $this->body,
            user_id: $this->user_id,
            views_count: $this->views_count,
            answers_count: $this->answers_count,
            comments_count: $this->comments_count,
            upvotes_count: $this->upvotes_count,
            downvotes_count: $this->downvotes_count,
            best_answer_id: $this->best_answer_id,
            bestAnswer: null,
            author: $this->author->toDTO(),
            tags: gettype($this->tags) == 'array' ? $this->tags : null,
            answers: gettype($this->answers) == 'array' ? $this->answers : null,
            created_at: $this->created_at,
            updated_at: $this->updated_at,
            created_date: (new Carbon($this->created_at))->diffForHumans(),
            updated_date: (new Carbon($this->updated_at))->diffForHumans(),
            has_question_upvote: $authUser ? $authUser->hasQuestionUpvote($this->id) : false,
            has_question_downvote: $authUser ? $authUser->hasQuestionDownvote($this->id) : false
        );
    }
    /**
     * ACCESSORS
     */
    public function getCreatedDateAttribute()
    {
        return $this->created_at->diffForHumans();
    }
    public function getAnswerStyleAttribute()
    {
        if($this->answers_count > 0) {
            if($this->best_answer_id) {
                return "bi bi-check-circle-fill text-success";
            }
            return "bi bi-check-circle";
        }
        return "bi bi-x-circle-fill text-danger";
    }
    /**
     * MUTATORS
     */
    public function setTitleAttribute(string $title)
    {
        $this->attributes['title'] = $title;
        $this->attributes['slug'] = Str::slug($title);
    }
    /**
     * RELATIONSHIP METHODS
     */
    public function author()
    {
        return $this->belongsTo(User::class, 'user_id');
    }
    public function answers()
    {
        return $this->hasMany(Answer::class);
    }
    public function tags()
    {
        return $this->belongsToMany(Tag::class)->withTimestamps();
    }
    public function votes()
    {
        return $this->morphToMany(User::class, 'vote')->withTimestamps();
    }
    public function bestAnswer()
    {
        return $this->hasOne(Answer::class, 'id')->with(['question', 'author', 'votes']);
    }
    /**
     * DB Helper Methods
     */

    public static function storeQuestion(QuestionDTO $questionDTO): self | Exception
    {
        Utils::validateOrThrow(self::CREATE_RULES, $questionDTO->toArray());
        $question = null;
        DB::transaction(function () use(&$question, $questionDTO) {
            $question = auth()->user()->questions()->create([
                'title' => $questionDTO->title,
                'body' => $questionDTO->body,
                'views_count'=> 0,
                'answers_count'=> 0,
                'upvotes_count'=> 0,
                'downvotes_count'=> 0,
            ]);
            $question->tags()->attach($questionDTO->tags);
        });
        return $question;
    }

    public function updateQuestion(QuestionDTO $questionDTO): self | Exception
    {
        Utils::validateOrThrow(self::UPDATE_RULES, $questionDTO->toArray());
        DB::transaction(function () use($questionDTO){
            $this->fill([
                'title' => $questionDTO->title,
                'body' => $questionDTO->body,
            ]);
            $this->tags()->sync($questionDTO->tags);
            // if($this->isClean()) {
            //     throw new Exception('You must change some value to update', 422);
            // }
            $this->save();
        });
        return $this;
    }

    public function markAsBestAnswer(int $answerId)
    {
        DB::transaction(function () use($answerId) {
            $this->update([
                'best_answer_id' => $answerId,
            ]);
        });
    }
}

app/Http/Controllers/Frontend/FrontendAnswersController.php
<?php

namespace App\Http\Controllers\Frontend;

use App\DTO\Answers\AnswerDTO;
use App\DTO\Questions\QuestionDTO;
use App\Http\Controllers\Controller;
use App\Models\Answer;
use App\Models\Question;

class FrontendAnswersController extends Controller
{
    public function edit(Question $question, Answer $answer)
    {
        $questionDTO = new QuestionDTO(...$question->toArray());
        $question = $questionDTO;
        $answerDTO = new AnswerDTO(...$answer->toArray());
        $answer = $answerDTO;
        return view('frontend.answers.edit', compact(['question','answer']));
    }
}

app/Http/Controllers/Frontend/FrontendQuestionsController.php
<?php

namespace App\Http\Controllers\Frontend;

use App\Http\Controllers\Controller;
use App\Models\Question;
use App\Models\Tag;
use App\Services\QuestionService;

class FrontendQuestionsController extends Controller
{
    private $questionService;
    public function __construct()
    {
        $this->middleware('can:performAuthorActions,question')->only('edit');
        $this->questionService = new QuestionService();
    }
    public function index()
    {
        $questions = $this->questionService->index();
        return view('frontend.questions.index', compact(['questions']));
    }

    public function show(int $id)
    {
        $question = $this->questionService->show($id);
        return view('frontend.questions.show', compact(['question']));
    }

    public function create()
    {
        $tags = Tag::all();
        return view('frontend.questions.create', compact(['tags']));
    }

    public function edit(Question $question)
    {
        $tags = Tag::all();
        return view('frontend.questions.edit', compact(['question', 'tags']));
    }

}

app/Http/Controllers/Frontend/FrontendTagsController.php
<?php

namespace App\Http\Controllers\Frontend;

use App\Http\Controllers\Controller;
use App\Models\Tag;
use Illuminate\Http\Request;

class FrontendTagsController extends Controller
{
    public function __construct()
    {
        $this->middleware('can:update,tag')->only('edit');
    }

    public function index()
    {
        $tags = Tag::with('creator')->latest()->paginate(15);
        return view('frontend.tags.index', compact(['tags']));
    }

    public function show(int $id)
    {
        $tag = Tag::with('creator')->findOrFail($id);
        $questions = $tag->questions()->latest()->paginate(3);
        return view('frontend.tags.show', compact(['tag', 'questions']));
    }

    public function create()
    {
        return view('frontend.tags.create');
    }

    public function edit(Tag $tag)
    {
        return view('frontend.tags.edit', compact(['tag']));
    }

}

app/Http/Controllers/Frontend/FrontendUsersController.php
<?php

namespace App\Http\Controllers\Frontend;

use App\Http\Controllers\Controller;
use App\Models\User;
use Illuminate\Http\Request;

class FrontendUsersController extends Controller
{
    public function __construct()
    {
        $this->middleware('can:update,user')->only('edit');
    }
    public function index()
    {
        $users = User::latest()->paginate(10);
        return view('frontend.users.index', compact(['users']));
    }
    public function show(User $user)
    {
        $questions = $user->questions()->latest()->paginate(3);
        return view('frontend.users.show', compact(['user', 'questions']));
    }
    public function edit(User $user)
    {
        return view('frontend.users.edit', compact(['user']));
    }
    public function notifications()
    {
        $notifications = auth()->user()->notifications()->latest()->simplePaginate(10);
        return view('frontend.users.notifications', compact(['notifications']));
    }
}

app/Http/Controllers/QuestionsController.php
<?php

namespace App\Http\Controllers;

use App\DTO\Questions\QuestionDTO;
use App\Http\Requests\Questions\CreateQuestionRequest;
use App\Http\Requests\Questions\UpdateQuestionRequest;
use App\Models\Answer;
use App\Models\Question;
use App\Notifications\Questions\NewQuestionAdded;
use App\Services\QuestionService;
use Exception;

class QuestionsController extends Controller
{
    public function __construct(private QuestionService $questionService)
    {
        $this->middleware('can:performAuthorActions,question')->except('store');
    }
    public function store(CreateQuestionRequest $request)
    {
        try {
            $question = $this->questionService->store(new QuestionDTO(
                title: $request->title,
                body: $request->body,
                user_id: auth()->id(),
                tags: $request->tags,
            ));
            /** Send Notifications */
            $userMsg = "You question has been successfully posted!";
            auth()->user()->notify(new NewQuestionAdded($question, $userMsg));

            return redirect(route('frontend.questions.index'));
        } catch(Exception $e) {
            session()->flash('error', 'Some unexpected error' . $e);
            return redirect()->back();
        }
    }

    public function update(UpdateQuestionRequest $request, Question $question)
    {
        try {
            $this->questionService->update(new QuestionDTO(
                title: $request->title,
                body: $request->body,
                tags: $request->tags,
            ), $question);
            return redirect(route('frontend.questions.show', $question->id));
        } catch(Exception $e) {
            session()->flash('error', $e->getMessage());
            return redirect()->back();
        }
    }

    public function destroy(Question $question)
    {
        $question->delete();
        return redirect(route('frontend.questions.index'));
    }
    public function markAsBestAnswer(Question $question, Answer $answer)
    {
        try {
            $this->questionService->markAsBestAnswer($question, $answer);
            return redirect()->back();
        } catch (Exception $e) {
            session()->flash('error', $e->getMessage());
            return redirect()->back();
        }
    }
}

resources/views/frontend/questions/create.blade.php
@extends('layouts.frontend.layout')

@section('title', 'Ask Question')

@section('hero-header-left')
    <h2 class="hero-title m-0">Ask a Question</h2>
@endsection

@section('hero-body')
    <div class="bg-white p16 br-10">
        <form action="{{route('questions.store')}}" class="m-0" method="POST" enctype="multipart/form-data">
            @csrf
            <div class="form-group">
                <label class="mb4">Title</label>
                <input type="text"
                       name="title"
                       value="{{old('title')}}"
                       class="form-control br-10 p12"
                       placeholder="eg: What is Java?">
                @error('title')
                    <small id="errorHelp" class="form-text text-danger">{{ $message }}</small>
                @enderror
            </div>

            <div class="form-group">
                <label for="body">Body</label>
                <input id="body" type="hidden" name="body" value="{{ old('body')}}">
                <trix-editor input="body" class="p12" placeholder="Elaborate your question..."></trix-editor>
                @error('body')
                    <small id="errorHelp" class="form-text text-danger">{{ $message }}</small>
                @enderror
            </div>

            <div class="form-group">
                <label for="tags">Tags</label>
                <select name="tags[]" id="tags" class="form-control select2" multiple>
                    <option></option>

                    @foreach ($tags as $tag)
                       <option value="{{ $tag->id }}"
                            {{ (old('tags') && (in_array($tag->id, old('tags'))) ? 'selected' : '') }}>
                            {{$tag->name}}
                       </option>
                    @endforeach
                </select>
                @error('tags')
                    <small id="errorHelp" class="form-text text-danger">{{ $message }}</small>
                @enderror
            </div>

            <div class="form-group text-right">
                <button type="submit" class="btn btn-success py8">Submit</button>
            </div>
        </form>
    </div>
@endsection

@section('page-level-styles')
    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/trix/1.3.1/trix.min.css">
@endsection

@section('page-level-scripts')
<script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/trix/1.3.1/trix.js"></script>

    <script>
        $('.select2').select2({
            placeholder: "Select ....",
            allowClear: true
        });

        flatpickr('#published_at', {
            enableTime : true,
            dateFormat : "Y-m-d H:i",
            minDate : new Date(),
        });
    </script>
@endsection

resources/views/frontend/questions/edit.blade.php
@extends('layouts.frontend.layout')

@section('title', 'Edit Question')

@section('hero-header-left')
    <h2 class="hero-title m-0">Edit a Question</h2>
@endsection

@section('hero-body')
    <div class="bg-white p16 br-10">
        <form action="{{route('questions.update',$question->id)}}" class="m-0" method="POST" enctype="multipart/form-data">
            @csrf
            @method('PUT')
            <div class="form-group">
                <label class="mb4">Title</label>
                <input type="text"
                       name="title"
                       value="{{old('title', $question->title)}}"
                       class="form-control br-10 p12"
                       placeholder="eg: What is Java?">
            </div>

            <div class="form-group">
                <label for="body">Body</label>
                <input id="body" type="hidden" name="body" value="{{ old('body', $question->body)}}">
                <trix-editor input="body" class="p12" placeholder="Elaborate your question..."></trix-editor>
                @error('body')
                    <small id="emailHelp" class="form-text text-danger">{{ $message }}</small>
                @enderror
            </div>

            <div class="form-group">
                <label for="tags">Tags</label>
                <select name="tags[]" id="tags" class="form-control select2" multiple>
                    <option></option>

                    @foreach ($tags as $tag)
                        @if((old('tags') && (in_array($tag->id, old('tags')))) || $question->hasTag($tag->id) )
                            <option value="{{ $tag->id }}" selected> {{$tag->name}} </option>
                        @else
                            <option value="{{ $tag->id }}"> {{$tag->name}} </option>
                        @endif
                @endforeach
                </select>
                @error('tags')
                    <small id="emailHelp" class="form-text text-danger">{{ $message }}</small>
                @enderror
            </div>

            <div class="form-group text-right">
                <button type="submit" class="btn btn-success py8">Submit</button>
            </div>
        </form>
    </div>
@endsection

@section('page-level-styles')
    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/trix/1.3.1/trix.min.css">
@endsection

@section('page-level-scripts')
<script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/trix/1.3.1/trix.js"></script>

    <script>
        $('.select2').select2({
            placeholder: "Select ....",
            allowClear: true
        });

        flatpickr('#published_at', {
            enableTime : true,
            dateFormat : "Y-m-d H:i",
            minDate : new Date(),
        });
    </script>
@endsection

resources/views/frontend/questions/index.blade.php
@extends('layouts.frontend.layout')

@section('title', 'Questions')

@section('hero-header-left')
    <h2 class="hero-title m-0">Recent Questions</h2>
@endsection

@section('hero-header-right')
    <a href="{{route('frontend.questions.create')}}" class="btn btn-primary py12 px20">Ask a question</a>
@endsection

@section('hero-body')
    @foreach ($questions as $question)
        <div class="section-card mb12 p16">
            <div class="author-image mr12">
                <img src="{{$question->author->avatar}}" alt="User image">
            </div>
            <div class="section-details">
                <div class="section-header">
                    <span class="user-info">Asked by: <a href="{{route('frontend.users.show', $question->author->id)}}" class="author-name">{{$question->author->name}}</a> {{$question->created_date}}</span>
                    <div class="tags-container">
                        <span class="ml12">Tags:</span>
                        <div class="tags">
                            @foreach ($question->tags as $tag)
                                <a href="{{route('frontend.tags.show', $tag->id)}}" class="tag badge badge-pill bg-outline-info">{{$tag->name}}</a>
                            @endforeach
                        </div>
                    </div>
                </div>
                <div class="section-body">
                    <a href="{{route('frontend.questions.show', $question->id)}}"  class="section-title">{{$question->title}}</a>
                    <p class="section-content">{!! \Illuminate\Support\Str::limit($question->body, 200) !!}</p>
                </div>
                <div class="section-footer d-flex mt8">
                    <div class="section-stats">
                        <div class="stat answers-count">
                            <i class="bi bi-chat-right mr8"></i>{{$question->answers_count . " " .\Illuminate\Support\Str::plural('answer', $question->answers_count)}}
                        </div>
                        <div class="stat upvotes-count">
                            <i class="bi bi-caret-up-fill mr8"></i>{{$question->upvotes_count . " " .\Illuminate\Support\Str::plural('upvote', $question->upvotes_count)}}
                        </div>
                        <div class="stat views-count">
                            <i class="bi bi-eye-fill mr8"></i>{{$question->views_count . " " .\Illuminate\Support\Str::plural('view', $question->views_count)}}
                        </div>
                        @if($question->best_answer_id)
                            <span class="stat best-answer-badge">
                                <i class="bi bi-check-circle mr8"></i>Best answer given by {{$question->bestAnswer->author->name}}
                            </span>
                        @endif
                    </div>
                    <div class="view-question-btn-container">
                        <a href="{{route('frontend.questions.show', $question->id)}}"  class="view-question-btn br-10 btn btn-sm btn-outline-primary no-border">View this question</a>
                    </div>

                </div>
            </div>
        </div>
    @endforeach
@endsection