routes/web.php
<?php

use App\Http\Controllers\AnswersController;
use App\Http\Controllers\Frontend\FrontendAnswersController;
use App\Http\Controllers\Frontend\FrontendQuestionsController;
use App\Http\Controllers\Frontend\FrontendTagsController;
use App\Http\Controllers\Frontend\FrontendUsersController;
use App\Http\Controllers\QuestionsController;
use App\Http\Controllers\TagsController;
use App\Http\Controllers\UsersController;
use App\Http\Controllers\VotesController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();
/* AUTH ROUTES */
Route::middleware(['auth'])->group(function() {

    /* QUESTION */
    Route::resource('questions', QuestionsController::class)->except('show', 'create', 'edit');

    /* TAGS */
    Route::resource('tags', TagsController::class)->except('show', 'create', 'edit');

    /* ANSWER */
    Route::resource('questions.answers', AnswersController::class)->except('show', 'create', 'edit');
    Route::put('questions/{question}/answers/{answer}/mark-as-best', [QuestionsController::class, 'markAsBest'])->name('questions.answers.markAsBest');

    /* USER */
    Route::resource('users', UsersController::class)->except('show', 'create', 'edit');
});

/* FRONTEND ROUTES */

/* Question */
Route::get('/', [FrontendQuestionsController::class, 'index'])->name('frontend.questions.index');
Route::get('/questions/create', [FrontendQuestionsController::class, 'create'])->name('frontend.questions.create');
Route::get('/questions/{question}', [FrontendQuestionsController::class, 'show'])->name('frontend.questions.show');
Route::get('/questions/{question}/edit', [FrontendQuestionsController::class, 'edit'])->name('frontend.questions.edit');
Route::post('/questions/{question}/votes/{vote}', [VotesController::class, 'voteQuestion'])->name('questions.vote');

/* Tag */
Route::get('/tags', [FrontendTagsController::class, 'index'])->name('frontend.tags.index');
Route::get('/tags/create', [FrontendTagsController::class, 'create'])->name('frontend.tags.create');
Route::get('/tags/{tag}', [FrontendTagsController::class, 'show'])->name('frontend.tags.show');
Route::get('/tags/{tag}/edit', [FrontendTagsController::class, 'edit'])->name('frontend.tags.edit');

/* User */
Route::get('/users', [FrontendUsersController::class, 'index'])->name('frontend.users.index');
Route::get('/users/notifications', [FrontendUsersController::class, 'notifications'])->name('frontend.users.notifications'); // internally the auth()->id() will be taken by me
Route::get('/users/{user}', [FrontendUsersController::class, 'show'])->name('frontend.users.show');
Route::get('/users/{user}/edit', [FrontendUsersController::class, 'edit'])->name('frontend.users.edit');

/* Answer */
Route::get('/questions/{question}/answers/{answer}', [FrontendAnswersController::class, 'edit'])->name('frontend.questions.answers.edit');
Route::post('/questions/{question}/answers/{answer}/votes/{vote}', [VotesController::class, 'voteAnswer'])->name('questions.answers.vote');

app/Models/Question.php
<?php

namespace App\Models;

use App\Constants\QuestionConstants;
use App\DTO\Questions\QuestionDTO;
use App\Helpers\Utils;
use App\Helpers\Votable;
use Carbon\Carbon;
use Exception;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class Question extends Model implements QuestionConstants
{
    use HasFactory, Votable;

    protected $guarded = ['id'];

    /**
     * HELPER METHODS
     */
    public function hasTag(int $tag_id):bool
    {
        return in_array($tag_id, $this->tags->pluck('id')->toArray());
    }

    public function toDTO(): QuestionDTO
    {
        $authUser = auth()->user();
        return new QuestionDTO(
            id: $this->id,
            title: $this->title,
            slug: $this->slug,
            body: $this->body,
            user_id: $this->user_id,
            views_count: $this->views_count,
            answers_count: $this->answers_count,
            comments_count: $this->comments_count,
            upvotes_count: $this->upvotes_count,
            downvotes_count: $this->downvotes_count,
            best_answer_id: $this->best_answer_id,
            bestAnswer: null,
            author: $this->author->toDTO(),
            tags: gettype($this->tags) == 'array' ? $this->tags : null,
            answers: gettype($this->answers) == 'array' ? $this->answers : null,
            created_at: $this->created_at,
            updated_at: $this->updated_at,
            created_date: (new Carbon($this->created_at))->diffForHumans(),
            updated_date: (new Carbon($this->updated_at))->diffForHumans(),
            has_question_upvote: $authUser ? $authUser->hasQuestionUpvote($this->id) : false,
            has_question_downvote: $authUser ? $authUser->hasQuestionDownvote($this->id) : false
        );
    }
    /**
     * ACCESSORS
     */
    public function getCreatedDateAttribute()
    {
        return $this->created_at->diffForHumans();
    }
    public function getAnswerStyleAttribute()
    {
        if($this->answers_count > 0) {
            if($this->best_answer_id) {
                return "bi bi-check-circle-fill text-success";
            }
            return "bi bi-check-circle";
        }
        return "bi bi-x-circle-fill text-danger";
    }
    /**
     * MUTATORS
     */
    public function setTitleAttribute(string $title)
    {
        $this->attributes['title'] = $title;
        $this->attributes['slug'] = Str::slug($title);
    }
    /**
     * RELATIONSHIP METHODS
     */
    public function author()
    {
        return $this->belongsTo(User::class, 'user_id');
    }
    public function answers()
    {
        return $this->hasMany(Answer::class);
    }
    public function tags()
    {
        return $this->belongsToMany(Tag::class)->withTimestamps();
    }
    public function votes()
    {
        return $this->morphToMany(User::class, 'vote')->withTimestamps();
    }
    public function bestAnswer()
    {
        return $this->hasOne(Answer::class, 'id')->with(['question', 'author', 'votes']);
    }
    /**
     * DB Helper Methods
     */

    public static function storeQuestion(QuestionDTO $questionDTO): self | Exception
    {
        Utils::validateOrThrow(self::CREATE_RULES, $questionDTO->toArray());
        $question = null;
        DB::transaction(function () use(&$question, $questionDTO) {
            $question = auth()->user()->questions()->create([
                'title' => $questionDTO->title,
                'body' => $questionDTO->body,
                'views_count'=> 0,
                'answers_count'=> 0,
                'upvotes_count'=> 0,
                'downvotes_count'=> 0,
            ]);
            $question->tags()->attach($questionDTO->tags);
        });
        return $question;
    }

    public function updateQuestion(QuestionDTO $questionDTO): self | Exception
    {
        Utils::validateOrThrow(self::UPDATE_RULES, $questionDTO->toArray());
        DB::transaction(function () use($questionDTO){
            $this->fill([
                'title' => $questionDTO->title,
                'body' => $questionDTO->body,
            ]);
            $this->tags()->sync($questionDTO->tags);
            // if($this->isClean()) {
            //     throw new Exception('You must change some value to update', 422);
            // }
            $this->save();
        });
        return $this;
    }

    public function markAsBestAnswer(int $answerId)
    {
        DB::transaction(function () use($answerId) {
            $this->update([
                'best_answer_id' => $answerId,
            ]);
        });
    }
}

app/Models/User.php
<?php

namespace App\Models;

use App\DTO\Users\UserDTO;
use App\Scopes\UserScopes;
use Carbon\Carbon;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use HasFactory, Notifiable, UserScopes;

    const ADMIN = 1;
    const CONTRIBUTOR = 2;
    const USER = 3;
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
    /**
     * Accessors
     */
    public function getAvatarAttribute()
    {
        $size=40;
        $name = $this->name;
        return "https://ui-avatars.com/api/?name={$name}&rounded=true&size={$size}";
    }

    public function getUserRoleAttribute()
    {
        if($this->role == self::ADMIN) {
            return 'admin';
        }
        if($this->role == self::CONTRIBUTOR) {
            return 'contributor';
        }
        if($this->role == self::USER) {
            return 'user';
        }
    }
    /**
     * RELATIONSHIP METHODS
     */
    public function questions()
    {
        return $this->hasMany(Question::class);
    }
    public function answers()
    {
        return $this->hasMany(Answer::class);
    }
    public function tags()
    {
        return $this->hasMany(Tag::class);
    }
    public function votesQuestion()
    {
        return $this->morphedByMany(Question::class, 'vote')->withTimestamps();
    }
    public function votesAnswer()
    {
        return $this->morphedByMany(Answer::class, 'vote')->withTimestamps();
    }

     /**
     * Helper methods for Question
     */
    public function hasQuestionUpvote($question_id)
    {
        if(gettype($question_id) == "integer") {
            return auth()->user()->votesQuestion()->where(['vote' => 1, 'vote_id' => $question_id, 'vote_type'=> Question::class])->exists();
        }
        return false;
    }
    public function hasQuestionDownvote($question_id)
    {
        if(gettype($question_id) == "integer") {
            return auth()->user()->votesQuestion()->where(['vote' => -1, 'vote_id' => $question_id, 'vote_type'=> Question::class])->exists();
        }
        return false;
    }
    public function hasVoteForQuestion($question_id)
    {
        return ($this->hasQuestionUpvote($question_id) || $this->hasQuestionDownvote($question_id));
    }

    public function hasAnswerUpvote($answer_id)
    {
        if(gettype($answer_id) == "integer") {
            return auth()->user()->votesAnswer()->where(['vote' => 1, 'vote_id' => $answer_id, 'vote_type'=> Answer::class])->exists();
        }
        return false;
    }
    public function hasAnswerDownvote($answer_id)
    {
        if(gettype($answer_id) == "integer") {
            return auth()->user()->votesAnswer()->where(['vote' => -1, 'vote_id' => $answer_id, 'vote_type' => Answer::class])->exists();
        }
        return false;
    }
    public function hasVoteForAnswer($answer_id)
    {
        return ($this->hasAnswerUpvote($answer_id) || $this->hasAnswerDownvote($answer_id));
    }

    public function toDTO(): UserDTO
    {
        return new UserDTO(
            id: $this->id,
            name: $this->name,
            email: $this->email,
            about: $this->about,
            location: $this->location,
            role: $this->role,
            avatar: $this->avatar,
            reputation: $this->reputation,
            questions: gettype($this->questions) == 'array' ? $this->questions : null,
            answers: gettype($this->answers) == 'array' ? $this->answers : null,
            tags: gettype($this->tags) == 'array' ? $this->tags : null,
            created_at: $this->created_at,
            updated_at: $this->updated_at,
            created_date: (new Carbon($this->created_at))->diffForHumans(),
            updated_date: (new Carbon($this->updated_at))->diffForHumans(),
        );
    }
}

app/Http/Controllers/Frontend/FrontendAnswersController.php
<?php

namespace App\Http\Controllers\Frontend;

use App\DTO\Answers\AnswerDTO;
use App\DTO\Questions\QuestionDTO;
use App\Http\Controllers\Controller;
use App\Models\Answer;
use App\Models\Question;

class FrontendAnswersController extends Controller
{
    public function edit(Question $question, Answer $answer)
    {
        $questionDTO = new QuestionDTO(...$question->toArray());
        $question = $questionDTO;
        $answerDTO = new AnswerDTO(...$answer->toArray());
        $answer = $answerDTO;
        return view('frontend.answers.edit', compact(['question','answer']));
    }
}

app/Http/Controllers/Frontend/FrontendQuestionsController.php
<?php

namespace App\Http\Controllers\Frontend;

use App\Http\Controllers\Controller;
use App\Models\Question;
use App\Models\Tag;
use App\Services\QuestionService;

class FrontendQuestionsController extends Controller
{
    private $questionService;
    public function __construct()
    {
        $this->middleware('can:performAuthorActions,question')->only('edit');
        $this->questionService = new QuestionService();
    }
    public function index()
    {
        $questions = $this->questionService->index();
        return view('frontend.questions.index', compact(['questions']));
    }

    public function show(int $id)
    {
        $question = $this->questionService->show($id);
        return view('frontend.questions.show', compact(['question']));
    }

    public function create()
    {
        $tags = Tag::all();
        return view('frontend.questions.create', compact(['tags']));
    }

    public function edit(Question $question)
    {
        $tags = Tag::all();
        return view('frontend.questions.edit', compact(['question', 'tags']));
    }

}

app/Http/Controllers/Frontend/FrontendTagsController.php
<?php

namespace App\Http\Controllers\Frontend;

use App\Http\Controllers\Controller;
use App\Models\Tag;
use Illuminate\Http\Request;

class FrontendTagsController extends Controller
{
    public function __construct()
    {
        $this->middleware('can:update,tag')->only('edit');
    }

    public function index()
    {
        $tags = Tag::with('creator')->latest()->paginate(15);
        return view('frontend.tags.index', compact(['tags']));
    }

    public function show(int $id)
    {
        $tag = Tag::with('creator')->findOrFail($id);
        $questions = $tag->questions()->latest()->paginate(3);
        return view('frontend.tags.show', compact(['tag', 'questions']));
    }

    public function create()
    {
        return view('frontend.tags.create');
    }

    public function edit(Tag $tag)
    {
        return view('frontend.tags.edit', compact(['tag']));
    }

}

app/Http/Controllers/Frontend/FrontendUsersController.php
<?php

namespace App\Http\Controllers\Frontend;

use App\Http\Controllers\Controller;
use App\Models\User;
use Illuminate\Http\Request;

class FrontendUsersController extends Controller
{
    public function __construct()
    {
        $this->middleware('can:update,user')->only('edit');
    }
    public function index()
    {
        $users = User::latest()->paginate(10);
        return view('frontend.users.index', compact(['users']));
    }
    public function show(User $user)
    {
        $questions = $user->questions()->latest()->paginate(3);
        return view('frontend.users.show', compact(['user', 'questions']));
    }
    public function edit(User $user)
    {
        return view('frontend.users.edit', compact(['user']));
    }
    public function notifications()
    {
        $notifications = auth()->user()->notifications()->latest()->simplePaginate(10);
        return view('frontend.users.notifications', compact(['notifications']));
    }
}

app/Http/Controllers/UsersController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\Users\UpdateUserRequest;
use App\Models\User;
use Illuminate\Http\Request;

class UsersController extends Controller
{
    public function __construct()
    {
        $this->middleware('can:update,user')->only('update');
    }
    public function update(UpdateUserRequest $request, User $user)
    {
        $user->update([
            'name' => $request->name,
            'location' => $request->location,
            'about' => $request->about
        ]);
        return redirect(route('frontend.users.show', $user->id));
    }
}

resources/views/frontend/users/edit.blade.php
@extends('layouts.frontend.layout')

@section('title', 'Edit User')

@section('hero-header-left')
    <h2 class="hero-title m-0">Edit Profile</h2>
@endsection

@section('hero-body')
    <div class="p16 br-10">
        <form action="{{route('users.update', $user->id)}}" method="POST" enctype="multipart/form-data">
            @csrf
            @method('PUT')
            <div class="row justify-content-center w-100">
                <div class="form-group">
                    <div class="profile-image">
                        <img src="https://ui-avatars.com/api/?name={{$user->name}}&rounded=true&size=150" alt="User Image">
                    </div>
                </div>
            </div>
            <div class="w-50 mx-auto">
                <div class="row justify-content-between">
                    <div class="form-group">
                        <label for="">Name</label>
                        <input type="text"
                           name="name"
                           value="{{old('name', $user->name)}}"
                           class="form-control box-shadow br-10 p12"
                           placeholder="eg: John Doe">
                        @error('name')
                           <small id="errorHelp" class="form-text text-danger">{{ $message }}</small>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label for="">Location</label>
                        <input type="text"
                           name="location"
                           value="{{old('location', $user->location)}}"
                           class="form-control box-shadow br-10 p12"
                           placeholder="eg: India">
                        @error('location')
                           <small id="errorHelp" class="form-text text-danger">{{ $message }}</small>
                        @enderror
                    </div>
                </div>
                <div class="row">
                    <div class="form-group w-100">
                        <label for="">About</label>
                        <input id="about" type="hidden" name="about" value="{{ old('about', $user->about)}}">
                        <trix-editor input="about" class="box-shadow p12" placeholder="Say something about yourself"></trix-editor>
                        @error('about')
                           <small id="errorHelp" class="form-text text-danger">{{ $message }}</small>
                        @enderror
                    </div>
                </div>
                <div class="form-group text-right">
                    <button type="submit" class="btn btn-success py8">Submit</button>
                </div>
            </div>
        </form>
    </div>
@endsection

resources/views/frontend/users/index.blade.php
@extends('layouts.frontend.layout')

@section('title', 'Users')

@section('hero-header-left')
    <h2 class="hero-title m-0">Users</h2>
    <div class="d-flex align-items-center my8 w100">
        <p class="count m-0">{{$users->count()}} users</p>
        <ul class="fast-filters list-group list-group-horizontal align-items-center">
            <li class="list-group-item list-group-item-action p-0">
                <a href="" class="fast-filter">All</a>
            </li>
            <li class="list-group-item list-group-item-action p-0">
                <a href="" class="fast-filter">New</a>
            </li>
            <li class="list-group-item list-group-item-action p-0">
                <a href="" class="fast-filter">Reputation</a>
            </li>
            <li class="list-group-item list-group-item-action p-0">
                <a href="" class="fast-filter">Admins</a>
            </li>
            <li class="list-group-item list-group-item-action p-0">
                <a href="" class="fast-filter">Contributors</a>
            </li>
        </ul>
        <form action="" class="input-group d-flex search-field w25">
            <input type="text"
                    name="user-search"
                    value="{{ request('search')}}"
                    class="form-control"
                    placeholder="Search a user...">
            <div class="input-group-append">
                <button type="submit" name="submit" class="btn btn-sm bg-white">
                    <i class="bi bi-search"></i>
                </button>
            </div>
        </form>
    </div>
@endsection

@section('hero-body')
    <div class="d-flex flex-wrap">
        @foreach ($users as $user)
            <div class="section-card d-inline-block user-card mb12 mr20 p16">
                <div class="user-card-header">
                    <div class="user-image">
                        <img src="{{asset($user->avatar)}}" alt="User image">
                    </div>
                    <div class="user-details">
                        <a href="{{route('frontend.users.show', $user->id)}}" class="user-name">{{$user->name}}</a>
                        <span class="user-location">{{$user->location}}</span>
                    </div>
                </div>
                <div class="user-stats">
                    <p><span class="stat">{{$user->reputation}}</span> reputation</p>
                    <p><span class="stat">{{$user->answers->count()}}</span> answers</p>
                    <p><span class="stat">{{$user->questions->count()}}</span> questions</p>
                </div>
                <span class="m-0 badge badge-pill bg-outline-primary">{{$user->user_role}}</span>
            </div>
        @endforeach
    </div>
@endsection
@section('hero-footer')
    {{ $users->links() }}
@endsection

resources/views/frontend/users/notifications.blade.php
@extends('layouts.frontend.layout')

@section('title', 'Notifications')

@section('hero-header-left')
    <h2 class="hero-title m-0">Notifications</h2>
@endsection

@section('hero-body')
    <ul class="section-card list-group">
        @foreach ($notifications as $notification)
            <li class="list-group-item">
                @switch($notification->type)
                    @case(\App\Notifications\Questions\NewQuestionAdded::class)
                        <div class="d-flex justify-content-between">
                            <div>
                                <i class="bi bi-check-circle-fill text-success"></i>
                                <span>{{$notification->data['msg']}} - </span>
                                <a href="{{route('frontend.questions.show', $notification->data['question']['id'])}}"class="text-dark" >
                                    <strong class="mx-1">
                                        <i class="bi bi-question-circle mr-1" title="Icon representing question asked"></i>
                                        See the question
                                    </strong>
                                </a>
                                @if ($notification->read_at == NULL)
                                  <span class="badge badge-sm bg-danger text-white ml-1">NEW</span>
                                @endif
                            </div>
                            <div>
                                <span class="text-muted float-right">{{$notification->created_at->diffForHumans()}}</span>
                            </div>
                        </div>
                        @break
                @endswitch
        @endforeach
    </ul>
    {{auth()->user()->unreadNotifications->markAsRead()}}
@endsection

resources/views/frontend/users/show.blade.php
@extends('layouts.frontend.layout')

@section('title', 'User')

@section('hero-header-left')
    <h2 class="hero-title m-0">User Profile</h2>
@endsection

@can('update', $user)
    @section('hero-header-right')
        <a href="{{route('frontend.users.edit', $user->id)}}" class="btn btn-info py12 px20">Edit Profile</a>
    @endsection
@endcan

@section('hero-body')
    <div class="row">
        <div class="profile-image">
            <img src="https://ui-avatars.com/api/?name={{$user->name}}&rounded=true&size=150" alt="User Image">
        </div>
        <div class="profile-details mx20">
            <h2 class="user-name mb4">{{$user->name}}</h2>
            <p class="user-location mb4"><i class="bi bi-geo-alt-fill"></i> {{$user->location}}</p>
            <div class="user-stats">
                <p class="stat-container mb4">Reputation earned - <span class="stat">{{$user->reputation}}</span></p>
                <p class="stat-container mb4">Questions asked - <span class="stat">{{$user->questions->count()}}</span></p>
                <p class="stat-container mb4">Answers given - <span class="stat">{{$user->answers->count()}}</span></p>
            </div>
            <p class="user-about mb4">{{$user->about}}</p>

        </div>
    </div>
    <div class="row mt20">
        <div class="user-activity w100">
            <p class="section-heading">User Activity</p>
            @if($user->questions->count() > 0)
                <ul class="fast-filters list-group list-group-horizontal align-items-center w25 mx-0">
                    <li class="list-group-item list-group-item-action p-0">
                        <a href="" class="fast-filter">Questions asked</a>
                    </li>
                    <li class="list-group-item list-group-item-action p-0">
                        <a href="" class="fast-filter">Answers given</a>
                    </li>
                </ul>
                <table class="table table-bordered mb-0 mt8">
                    <thead class="thead-dark">
                        <tr>
                            <th>Question Title</th>
                            <th class="text-center">Got Answer</th>
                            <th>Date</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach ($questions as $question)
                            <tr>
                                <td>{{$question->title}}</td>
                                <td class="text-center status"><i class="{{$question->answer_style}}"></i></td>
                                <td>July 26, 2021 at 12:05</td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
                <div class="text-right mb16 mt8">
                    See all <strong><a href="">Questions</a></strong> and <strong><a href="">Answers -></a></strong>
                </div>
                <div class="alert bg-outline-info alert-dismissible fade show" role="alert">
                    <strong class="tips">
                        Quick Tip:
                        <span class="tip mx16">
                            <i class="bi bi-check-circle mr2"></i> Question was answered
                        </span>
                        <span class="tip mr16">
                            <i class="bi bi-check-circle-fill text-success mr2"></i> Question has best answer
                        </span>
                        <span class="mr16">
                            <i class="bi bi-x-circle-fill text-danger mr2"></i> Question was not answered
                        </span>
                    </strong>
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                    </button>
                </div>
            @else
                <div class="empty-state-card">
                    <div class="empty-state-card-body">
                        <img src="{{asset('frontend/assets/illustrations/user-activity.svg')}}" alt="empty activity">
                        <p class="mt20 mb20">All the activities done by user will be displayed here</p>
                    </div>
                </div>
            @endif

        </div>
    </div>
@endsection